name: tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  formula:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-15-intel, ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: Homebrew/actions/setup-homebrew@848c272c7bfe984a197bd4d16383f4c106ec61e6 # main
      - run: brew style dino-hq/tap
      - run: brew audit --strict dino-hq/tap/dino
      - run: brew install dino-hq/tap/dino
      - run: brew test dino-hq/tap/dino
      - run: dino --version
